logging:
  log_dir: "/raid/vision/dhchoi/log/tha"
  seed: "1"
  nepochs: 100
  device: cuda
  save_optimizer_state: False

  freq:
    log: 100
    save: 1 # epoch

  savefiles: [
      '*.py',
      '*.sh',
      'configs/*.*',
      'configs/dataset/*.*',
      'datasets/*.*',
      'models/*.*',
      'utils/*.*',
  ]


datasets:
  train:
    class: datasets.base.MultiDataset
    datasets: [
        'configs/datasets/custom.yaml',
    ]

    mode: train
    batch_size: 32
    shuffle: True
    num_workers: 16


models:
  FaceMorpher:
    class: models.tha1.FaceMorpher

    optims:
      class: torch.optim.Adam
      kwargs:
        lr: 1e-4
        betas: [ 0.5, 0.9 ]














